# Generated by Django 5.2.5 on 2025-08-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('employee', 'Employee'), ('guest', 'Guest')], default='admin', max_length=10),
        ),
    ]
