# Generated by Django 5.2.5 on 2025-08-13 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='work_shift',
            field=models.CharField(choices=[('day', 'Day'), ('mid', 'Mid'), ('night', 'Night')], default='day', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('employee', 'Employee'), ('guest', 'Guest')], default='employee', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('approve', 'Approve'), ('declined', 'Declined'), ('completed', 'Completed')], default='approve', max_length=10),
        ),
        migrations.CreateModel(
            name='ShiftToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allotted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allotted_tokens', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'shift'],
                'unique_together': {('user', 'date', 'shift')},
            },
        ),
        migrations.DeleteModel(
            name='MonthlyToken',
        ),
    ]
