# Generated by Django 5.2.5 on 2025-08-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_work_shift_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shifttoken',
            options={'ordering': ['-id', 'shift']},
        ),
        migrations.AlterUniqueTogether(
            name='shifttoken',
            unique_together={('user', 'shift')},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.RemoveField(
            model_name='shifttoken',
            name='allotted_by',
        ),
        migrations.RemoveField(
            model_name='shifttoken',
            name='date',
        ),
        migrations.RemoveField(
            model_name='shifttoken',
            name='updated_at',
        ),
    ]
