# Generated by Django 5.2.3 on 2025-08-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_order_status_monthlytoken_delete_shifttoken'),
    ]

    operations = [
    ]
