# Generated by Django 5.2.5 on 2025-08-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_token_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyToken',
        ),
    ]
