# Generated by Django 5.2.5 on 2025-08-23 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_monthlytoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('day', 'Day'), ('mid', 'Mid'), ('night', 'Night')], max_length=10)),
                ('tokens_per_user', models.PositiveIntegerField()),
                ('users_updated', models.PositiveIntegerField(default=0)),
                ('month_year', models.DateField(help_text='First day of the month this distribution applies to')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_distributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Distribution',
                'verbose_name_plural': 'Token Distributions',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTokenAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_tokens', models.PositiveIntegerField(default=0)),
                ('assigned_tokens', models.PositiveIntegerField(default=0)),
                ('new_tokens', models.PositiveIntegerField(default=0)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.tokendistribution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Token Assignment',
                'verbose_name_plural': 'User Token Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
