# Generated by Django 5.2.5 on 2025-08-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tokendistribution_usertokenassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('employee', 'Employee'), ('guest', 'Guest')], db_index=True, default='employee', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='work_shift',
            field=models.CharField(choices=[('day', 'Day'), ('mid', 'Mid'), ('night', 'Night')], db_index=True, default='day', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='tokendistribution',
            constraint=models.UniqueConstraint(fields=('shift', 'month_year'), name='unique_distribution_per_shift_month'),
        ),
        migrations.AddConstraint(
            model_name='usertokenassignment',
            constraint=models.UniqueConstraint(fields=('distribution', 'user'), name='unique_assignment_per_user_per_distribution'),
        ),
    ]
