# Generated by Django 5.2.5 on 2025-08-23 18:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_customuser_role_alter_customuser_work_shift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTokenAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('day', 'Day'), ('mid', 'Mid'), ('night', 'Night')], db_index=True, max_length=10)),
                ('tokens_per_user', models.PositiveIntegerField(default=0)),
                ('allocation_month', models.DateField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='usertokenassignment',
            name='unique_assignment_per_user_per_distribution',
        ),
        migrations.RemoveField(
            model_name='usertokenassignment',
            name='distribution',
        ),
        migrations.RemoveField(
            model_name='usertokenassignment',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='tokendistribution',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='tokendistribution',
            name='unique_distribution_per_shift_month',
        ),
        migrations.RenameField(
            model_name='tokendistribution',
            old_name='users_updated',
            new_name='tokens_allocated',
        ),
        migrations.AddField(
            model_name='tokendistribution',
            name='allocation_month',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tokendistribution',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_distributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('employee', 'Employee'), ('guest', 'Guest')], default='employee', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='work_shift',
            field=models.CharField(choices=[('day', 'Day'), ('mid', 'Mid'), ('night', 'Night')], default='day', max_length=10),
        ),
        migrations.AddIndex(
            model_name='tokendistribution',
            index=models.Index(fields=['user', 'allocation_month'], name='api_tokendi_user_id_bf22ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tokendistribution',
            unique_together={('user', 'allocation_month')},
        ),
        migrations.AddIndex(
            model_name='shifttokenallocation',
            index=models.Index(fields=['shift', 'allocation_month'], name='api_shiftto_shift_d62bf2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shifttokenallocation',
            unique_together={('shift', 'allocation_month')},
        ),
        migrations.DeleteModel(
            name='UserTokenAssignment',
        ),
        migrations.RemoveField(
            model_name='tokendistribution',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='tokendistribution',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='tokendistribution',
            name='month_year',
        ),
        migrations.RemoveField(
            model_name='tokendistribution',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='tokendistribution',
            name='tokens_per_user',
        ),
    ]
